### PR TITLE
feature/dont-delete-album

### PR DESCRIPTION
**Pull request by pjosh**
Removing the option of delete an album

### CODE REVIEW

**Comment by simaob** [comment]
I think they want to be able to delete an album, not the other way around.

**Comment by pjosh** [comment]
@simaob sure?
I tried in my local and all works good, so... I thought that they wanted to remove this option.

**Comment by simaob** [comment]
I think so. I remember them asking for this.

Maybe ask for an example of when it failed.

**Comment by pjosh** [comment]
ok @simaob !!
I'll close this PR and I'll ask to Rob about it.

**Pull request closed without merging**
