### PR TITLE
Allow two lines title in CMS. 

### PR DESCRIPTION
**Pull request by dhakelila**
This: https://basecamp.com/1756858/projects/12531475/todos/289591856

### CODE REVIEW

**Comment by dhakelila** [comment]
The last two commits fix the issue with sections where we have two textareas together. Now they look ok, and the styles to avoid the flash notice crash.

Note that we need a "two rows" textarea to allow long title display, but this generates a bigger input that makes that header look a bit bigger. 

Note also that the textarea in the "user section", won't allow 2 lines. There is a bug that causes short words drop the last letter even if there is enough space for it. That is why I was forced to use `white-space: no-wrap`. To avoid that letter drops. But that rule is the same that keeps the line from splitting in two when they are too long. 

Please, @pjosh, review the styles, as you know the project better than me, to avoid accidental crashes due to my changes.

**Comment by simaob** [comment]
I feel that for records that require multiple inputs on the title (like Users (maybe just Users)), shouldn't really get two textareas but just two normal inputs. we could check if there are multiple inputs and use text_fields in that case, and textareas if there's only one.

**Comment by pjosh** [comment]
Now, with the current behavior (on develop), we have a JS (`form_adjustable_input.js`) who resize the input based on the text value. I think this behavior doesn't have sense with a 2 lines textarea because this is only for keep the pencil icon near the input. Apart from this, with the textarea, we have a strange behaviour: https://drive.google.com/file/d/0BxqkgRZYI739LU9hZ0t3TnREMms/view
I think we should eliminate this JS.

About the flash notification, Juan Carlos will give us a design similar to this http://codepen.io/mcraiganthony/pen/wMVPXy who doesn't break any styles because it will be an absolute block over the form.

**Comment by simaob** [comment]
Is this ready for another review? =)

**Comment by simaob** [comment]
ping? @dhakelila

**Comment by dhakelila** [comment]
Sorry. Yes. This is ready. Not the test though... :/

**Comment by simaob** [comment]
OK, so the tests seem to be related with us not handling the error anymore. If the title of a section or other records is not set it's not showing in red as it was before.

Can the two of you have a look at it @pjosh && @dhakelila 

It used to be like this:

screen shot 2017-01-12 at 09 59 03

**Pull request merged**
