### PR TITLE
Feature/cms events section

### PR DESCRIPTION
**Pull request by pjosh**
* Events section 
* Refactor index items buttons to be more DRY

### CODE REVIEW

**Comment by simaob** [comment]
Noticed a small bug with the javascript that might be affecting the other CRUD messages: When I submit the form with errors the textareas are not parsing the HTML see attached screenshot:

screen shot 2016-11-23 at 14 26 53

**Comment by pjosh** [comment]
@simaob you are right! I see that, when the errors appear, the `update` method redirect to the `index` url.
I'll fixed!

**Comment by pjosh** [comment]
Done @simaob! thx!

**Comment by simaob** [comment]
Not to be a pain in the ass... but though it is fixed when creating a new event. It isn't if I try to update one and I cause the error.

**Pull request merged**
